apiVersion: v1
kind: Secret
metadata:
  name: tfg-backend-secrets
type: Opaque
stringData: 
  USER_EMAIL: soporte@meteostats.es
  PASS_EMAIL: 
  USERNAME_CASSANDRA: cassandra
  PASSWORD_CASSANDRA: cassandra 
  APIKEY_WEATHER: fd10b0dcb392959b10aa51f78462f9fd
---
apiVersion: v1
kind: Secret
metadata:
  name: tfg-frontend-secrets
type: Opaque
stringData: 
  GOOGLE_API_KEY: AIzaSyBsZnTlM4g1LCqmg4u74pouNXE3mlQF6Uk
