version: '3'
services:
  frontend:
    build:
      context:  ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend
  backend:
     build:
      context:  ./backend
     networks:
        - mynetwork
     ports:
        - "5000:5000"
networks:
  mynetwork:
    driver: bridge
    ipam:
       config:
         - subnet: 10.10.10.0/29
