apiVersion: v1
kind: Secret
metadata:
  name: tfg-backend-secrets
type: Opaque
stringData: 
  USER_EMAIL: soporte@meteostats.es
  PASS_EMAIL: pass
  USERNAME_CASSANDRA: cassandra
  PASSWORD_CASSANDRA: cassandra 
  APIKEY_WEATHER: apikey
---
apiVersion: v1
kind: Secret
metadata:
  name: tfg-frontend-secrets
type: Opaque
stringData: 
  GOOGLE_API_KEY: apikey
