version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - CASSANDRA=10.88.0.46
      - DATACENTER=datacenter1
      - PORT=9042
      - KEYSPACE=tfg
    networks:
      - red

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - SERVIDOR=10.88.0.2
    networks:
      - red
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      volumes:
        - ./bbdd/inicio.cql:/inicio.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /inicio.cql"
      networks:
        - red
networks:
  red:
    driver: bridge
