version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - CASSANDRA=cassandra
      - DATACENTER=datacenter1
      - PORT=9042
      - KEYSPACE=tfg
    networks:
      - red
    depends_on:
      - cassandra
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - SERVIDOR=10.88.0.2
    networks:
      - red
  cassandra:
    build:
      context: ./bbdd
    networks:
      - red
    ports:
      - "9042:9042"
networks:
  red:
    driver: bridge
